services:
  db:
    image: postgres:17-alpine
    restart: always # Если сервер упадет, база сама поднимется
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    env_file:
      - .envs/.production/.postgres

  web:
    build: .
    # Используем Gunicorn (он мощнее и быстрее для реальных людей)
    # Укажи тут путь к своему wsgi. Обычно это 'название_проекта.wsgi'
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "80:8000" # Проект будет доступен просто по IP или домену
    env_file:
      - .envs/.production/.django
    depends_on:
      - db

volumes:
  prod_db_data: