services:
  # Наша база данных
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.postgres

  # Наш Django проект
  web:
    build: .
    # Запускаем обычный сервер для разработки
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # Это важно: изменения в коде на компе сразу полетят в контейнер
    ports:
      - "8000:8000"
    env_file:
      - .envs/.local/.django
    depends_on:
      - db

volumes:
  postgres_data: